[Settings]

[build]
  command = "npm run export"
  publish = "out/"

[build.environment]
  NODE_VERSION = "15.5.0"

[[redirects]]
  from = "/discord"
  to = "https://discord.gg/b8U5Hdy"
  status = 301
  force = true

[[redirects]]
  from = "/_next/static/service-worker.js"
  to = "/service-worker.js"
  status = 301
  force = true

[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Service-Worker-Allowed = "/"
    Cache-Control = "public, max-age=43200, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
        base-uri 'self';
        connect-src 'self' cdn.jsdelivr.net;
        default-src 'none';
        font-src 'self' cdn.jsdelivr.net;
        form-action 'self';
        frame-ancestors 'none';
        frame-src 'self';
        img-src 'self' data:;
        manifest-src 'self';
        media-src 'self';
        object-src 'none';
        prefetch-src 'self';
        script-src 'self' 'unsafe-inline' cdn.jsdelivr.net;
        style-src 'self' 'unsafe-inline' cdn.jsdelivr.net;
        upgrade-insecure-requests;
    """
    Expect-CT = "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\""
    Permissions-Policy = "fullscreen 'self';"
    Referrer-Policy = "strict-origin"
    Strict-Transport-Security = "max-age=31557600; includesubdomains; preload"
    Vary = "Accept-Encoding"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "deny"
    X-XSS-Protection = "1; mode=block"
